create or replace NONEDITIONABLE PACKAGE PKG_LODGING AS 

  -- 숙소 입력
  PROCEDURE PROC_INS_LOD(
	 IN_HOST_ID		IN		VARCHAR2
	,IN_G_COM_ID	IN		VARCHAR2
	,IN_L_COM_ID	IN		VARCHAR2
	,IN_L_NAME		IN		VARCHAR2
	,IN_CHECK_IN	IN		VARCHAR2
	,IN_CHECK_OUT	IN		VARCHAR2
	,O_ERRCODE		OUT		VARCHAR2
	,O_ERRMSG		OUT		VARCHAR2
  );

  
  -- 숙소 조회
  PROCEDURE PROC_SEL_LOD(
	 IN_L_ID		IN		VARCHAR2
	,IN_H_ID		IN		VARCHAR2
	,IN_G_COM_ID	IN		VARCHAR2
	,IN_G_COM_ID2	IN		VARCHAR2
	,IN_L_COM_ID	IN		VARCHAR2
	,IN_L_COM_ID2	IN		VARCHAR2
	,IN_L_NAME		IN		VARCHAR2
	,IN_L_SCOPE_S	IN		VARCHAR2
	,IN_L_SCOPE_E	IN		VARCHAR2
	,IN_CHECKIN_TIME    IN 	VARCHAR2		-- 체크인 시간
    ,IN_CHECKOUT_TIME	IN 	VARCHAR2		-- 체크아웃 시간
	,O_CUR			OUT		SYS_REFCURSOR
  );
  
  -- 숙소 수정
  PROCEDURE PROC_UP_LOD(
	IN_L_ID			IN		VARCHAR2
	,IN_G_COM_ID	IN		VARCHAR2
	,IN_L_COM_ID	IN		VARCHAR2
	,IN_L_NAME		IN		VARCHAR2
	,IN_CHECK_IN	IN		VARCHAR2
	,IN_CHECK_OUT	IN		VARCHAR2
	,O_ERRCODE		OUT		VARCHAR2
	,O_ERRMSG		OUT		VARCHAR2
  );
  
  -- 숙소 삭제
  PROCEDURE PROC_DEL_LOD(
	IN_L_ID			IN		VARCHAR2
	,O_ERRCODE		OUT		VARCHAR2
	,O_ERRMSG		OUT		VARCHAR2
  );
  
END PKG_LODGING;