create or replace NONEDITIONABLE PACKAGE PKG_HOST AS 

  -- 호스트 생성
  PROCEDURE PROC_INS_HOST(
	 IN_HOST_NUM		IN		VARCHAR2
	,IN_HOST_NAME		IN		VARCHAR2
	,O_ERRCODE			OUT		VARCHAR2
	,O_ERRMSG			OUT		VARCHAR2
  );
  
   
 -- 호스트 읽기
  PROCEDURE PROC_SEL_HOST(
	 IN_HOST_ID			IN		VARCHAR2
	 ,IN_HOST_NUM		IN		VARCHAR2
	 ,IN_HOST_NAME 		IN		VARCHAR2
	 ,IN_HOST_LVL		IN		VARCHAR2
	 ,O_CUR				OUT		SYS_REFCURSOR
  );
  
  
  -- 호스트 수정
  PROCEDURE PROC_UP_HOST(
	  IN_HOST_ID		IN		VARCHAR2
	 ,IN_HOST_NUM		IN		VARCHAR2
	 ,IN_HOST_NAME		IN		VARCHAR2
	 ,O_ERRCODE			OUT		VARCHAR2
	 ,O_ERRMSG			OUT		VARCHAR2
  );

  -- 호스트 삭제 
  PROCEDURE PROC_DEL_HOST(
	IN_HOST_ID			IN		VARCHAR2
	,O_ERRCODE			OUT		VARCHAR2
	,O_ERRMSG			OUT		VARCHAR2
  );
  
END PKG_HOST;