create or replace NONEDITIONABLE PACKAGE PKG_RESERVATION_DETAIL AS 


  PROCEDURE PROC_INS_RESERVATION_DETAIL
(
    IN_RM_ID      IN VARCHAR2,
    IN_R_ID        IN VARCHAR2,
    O_ERRCODE			OUT		VARCHAR2,
    O_ERRMSG			OUT		VARCHAR2
);

  PROCEDURE PROC_UP_RESERVATION_MANAGE
(
	IN_RM_ID			    IN VARCHAR2,
    IN_ROOM_ID		    IN VARCHAR2,
    IN_RM_DATE 		    IN DATE,
    IN_RM_GUBUN		    IN VARCHAR2,
    IN_RM_PRICE		    IN NUMBER,
    IN_RM_PERSON         IN NUMBER,
    IN_RM_ADD_PERSON  IN NUMBER,
    IN_RM_ADD_PRICE     IN	NUMBER,
	O_ERRCODE			OUT		VARCHAR2,
    O_ERRMSG			OUT		VARCHAR2
);

  PROCEDURE PROC_SEL_RESERVATION_DETAIL
(
    IN_RD_ID      IN VARCHAR2,
    IN_RM_ID      IN VARCHAR2,
    IN_R_ID        IN VARCHAR2,
    O_CUR         OUT    SYS_REFCURSOR
);

  PROCEDURE PROC_DEL_RESERVATION_DETAIL
(
    IN_RD_ID      IN VARCHAR2,
    IN_RM_ID      IN VARCHAR2,
    IN_R_ID        IN VARCHAR2
);



END PKG_RESERVATION_DETAIL;