create or replace NONEDITIONABLE PACKAGE PKG_ROOM AS 

	-- 방 입력
	PROCEDURE PROC_INS_ROOM(
		 IN_L_ID		IN		VARCHAR2
		,IN_BED_EA		IN		VARCHAR2
		,IN_BEDROOM_EA	IN		VARCHAR2
		,IN_BATH_EA		IN		VARCHAR2
		,O_ERRCODE		OUT		VARCHAR2
		,O_ERRMSG		OUT		VARCHAR2
	);
	
	-- 방 조회
	PROCEDURE PROC_SEL_ROOM(
		 IN_ROOM_ID		IN		VARCHAR2
		,IN_L_ID		IN		VARCHAR2
		,IN_BED_EA		IN		VARCHAR2
		,IN_BEDROOM_EA	IN		VARCHAR2
		,IN_BATH_EA		IN		VARCHAR2
		,O_CUR			OUT		SYS_REFCURSOR
	);
	
	-- 방 수정 ( 방 ID와 건물 ID는 변경 불가능 )
	PROCEDURE PROC_UP_ROOM(
		 IN_ROOM_ID		IN		VARCHAR2
		,IN_BED_EA		IN		VARCHAR2
		,IN_BEDROOM_EA	IN		VARCHAR2
		,IN_BATH_EA		IN		VARCHAR2
		,O_ERRCODE		OUT		VARCHAR2
		,O_ERRMSG		OUT		VARCHAR2
	);
	
	-- 방 삭제
   PROCEDURE PROC_DEL_ROOM(
		 IN_ROOM_ID		IN		VARCHAR2
		,O_ERRCODE		OUT		VARCHAR2
		,O_ERRMSG		OUT		VARCHAR2
	);
	
END PKG_ROOM;