create or replace NONEDITIONABLE PACKAGE PKG_CUSTOMER AS 
  -- 고객 입력
  PROCEDURE PROC_INS_CUST(
	 IN_CUST_NAME	IN		VARCHAR2
	,IN_CUST_TEL	IN		VARCHAR2
	,IN_CUST_GUBUN	IN		VARCHAR2
	,O_ERRCODE		OUT		VARCHAR2
	,O_ERRMSG		OUT		VARCHAR2
  );
  
  -- 고객 조회
  PROCEDURE PROC_SEL_CUST(
	 IN_CUST_ID		IN		VARCHAR2
	,IN_CUST_NAME	IN		VARCHAR2
	,IN_CUST_TEL	IN		VARCHAR2
	,IN_CUST_GUBUN	IN		VARCHAR2
	,O_CUR			OUT		SYS_REFCURSOR
  );
  
      -- 고객 수정
  PROCEDURE PROC_UP_CUST(
	 IN_CUST_ID		IN		VARCHAR2
	,IN_CUST_NAME	IN		VARCHAR2
	,IN_CUST_TEL	IN		VARCHAR2
	,IN_GUBUN		IN		VARCHAR2
	,O_ERRCODE		OUT		VARCHAR2
	,O_ERRMSG		OUT		VARCHAR2
  );
  
  
  PROCEDURE PROC_DEL_CUST(
	 IN_CUST_ID		IN		VARCHAR2
	,O_ERRCODE		OUT		VARCHAR2
	,O_ERRMSG		OUT		VARCHAR2
  );

END PKG_CUSTOMER;