create or replace NONEDITIONABLE PACKAGE PKG_ROOM_DETAIL AS 

  -- 방 상세정보 입력
  PROCEDURE PROC_INS_ROOM_DETAIL(
		 IN_ROOM_ID 		IN		VARCHAR2
		,IN_COM_ID			IN		VARCHAR2
		,O_ERRCODE			OUT		VARCHAR2
		,O_ERRMSG			OUT		VARCHAR2
  );
  
  -- 방 상세정보 조회
  PROCEDURE PROC_SEL_ROOM_DETAIL(
		 IN_ROOM_DETAIL_ID	IN		VARCHAR2
		,IN_ROOM_ID			IN		VARCHAR2
		,IN_COM_ID			IN		VARCHAR2
		,O_CUR				OUT		SYS_REFCURSOR
  );

  -- 방 상세정보 수정
  PROCEDURE PROC_UP_ROOM_DETAIL(
		 IN_ROOM_DETAIL_ID	IN		VARCHAR2
		,IN_ROOM_ID			IN		VARCHAR2
		,IN_COM_ID			IN		VARCHAR2 
		,O_ERRCODE			OUT		VARCHAR2
		,O_ERRMSG			OUT		VARCHAR2
  );
  
  -- 방 상세정보 삭제 
  PROCEDURE PROC_DEL_ROOM_DETAIL(
		 IN_ROOM_DETAIL_ID	IN		VARCHAR2
		,O_ERRCODE			OUT		VARCHAR2
		,O_ERRMSG			OUT		VARCHAR2
  );



END PKG_ROOM_DETAIL;